version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: thebutton-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  thebutton:
    build: .
    container_name: thebutton-bot
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs
      - ./bot_code/message/audio_output:/app/bot_code/message/audio_output
    environment:
      - REDIS_HOST=redis
    restart: unless-stopped

volumes:
  redis_data:
